# Generated by Django 3.1.2 on 2020-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_auto_20201022_1053'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tribes',
        ),
        migrations.AddField(
            model_name='profile',
            name='tribes',
            field=models.ManyToManyField(blank=True, to='tribes.Tribe'),
        ),
    ]
