# Generated by Django 3.1.2 on 2020-10-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tribes',
            field=models.ManyToManyField(blank=True, to='users.Tribe'),
        ),
    ]
