# Generated by Django 3.1.2 on 2020-10-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_profile_tribes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tribes',
        ),
        migrations.DeleteModel(
            name='Tribe',
        ),
    ]
