# Generated by Django 3.1.2 on 2020-10-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201021_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe', models.CharField(blank=True, max_length=70)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('members', models.ManyToManyField(blank=True, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tribes',
            field=models.ManyToManyField(blank=True, to='users.Tribe'),
        ),
    ]
