# Generated by Django 3.1.2 on 2020-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201021_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribe',
            name='tribe',
        ),
        migrations.AddField(
            model_name='tribe',
            name='name',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
