# Generated by Django 3.1.2 on 2020-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201021_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
