# Generated by Django 3.1.2 on 2020-10-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='members',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribes.tribe'),
        ),
    ]
