# Generated by Django 3.1.2 on 2020-10-23 16:15

from django.db import migrations, models
import tribes.models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_auto_20201023_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='image',
            field=models.ImageField(default='default.png', upload_to=tribes.models.upload_path_handler),
        ),
    ]
