# Generated by Django 3.1.2 on 2020-10-22 17:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_auto_20201022_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
