# Generated by Django 3.1.2 on 2020-10-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201021_1431'),
        ('feed', '0002_auto_20201020_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tribe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to='users.tribe'),
        ),
    ]
