# Generated by Django 3.1.2 on 2020-10-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201021_1434'),
        ('feed', '0005_auto_20201021_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to='users.tribe'),
        ),
    ]
